'use client'
import { Inter } from "next/font/google";
import "./globals.scss";
import Header from "./global/modules/header/layout";
import { usePathname } from "next/navigation";
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import Head from "next/head";
import '../../primeConfig';
import { ThemeProvider, useTheme } from './context/ThemeContext';
import {AuthProvider} from './context/auth.jsx';
import {NextUIProvider} from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({Component, children }) {

  const routerPathName = usePathname();
  //  console.log(routerPathName);

  const noHeaderCheck = routerPathName !== '/auth/signin' && routerPathName !== '/auth/signup' && routerPathName !== '/auth/reset-password' && routerPathName !== '/mt-admin/login';

  return (
    <html lang="en">
      <ThemeProvider>
        
        <NextUIProvider>
        <AuthProvider>
          <body className={inter.className}>

            { noHeaderCheck ?(<Header/>):(null)}
            
            <main className={noHeaderCheck?'bodyWrapper':'signinupWrapper'}>{children}</main>
            
          </body>
          </AuthProvider>
          </NextUIProvider>
      
      </ThemeProvider>
    </html>
  );
}
