'use client';
import { Inter } from "next/font/google";
import "./globals.scss";
import dynamic from 'next/dynamic'; // Import the dynamic function
import { usePathname } from "next/navigation";
import Head from "next/head";
import '../../primeConfig';
import { ThemeProvider } from './context/ThemeContext';
import { AuthProvider } from './context/auth.jsx';
import { NextUIProvider } from "@nextui-org/react";

// Dynamically import the Header component
const Header = dynamic(() => import('./global/modules/header/layout'), { ssr: false });

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  const routerPathName = usePathname();

  const noHeaderCheck = routerPathName !== '/auth/signin' && 
                        routerPathName !== '/auth/signup' && 
                        routerPathName !== '/auth/reset-password' && 
                        routerPathName !== '/mt-admin/login';

  return (
    <html lang="en">
      <Head>
        {/* Add metadata and other head elements here if needed */}
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body className={inter.className}>
      <ThemeProvider>
        <NextUIProvider>
          <AuthProvider>
            
              {noHeaderCheck ? <Header /> : null}
              <main className={noHeaderCheck ? 'bodyWrapper' : 'signinupWrapper'}>
                {children}
              </main>
            
          </AuthProvider>
        </NextUIProvider>
      </ThemeProvider>
      </body>
    </html>
  );
}
